### ISSUE TITLE
Building changelog is mandatory

### ISSUE THREAD

**Issue by kdschlosser** [EventGhost/EventGhost#106] opened 2016-08-27 05:26 UTC
In order to build an Installer of EG it is required that a changelog is built. and it appears as though in order to build a changelog it is a requirement that the builder connects to a github account that i set up. I do not see how this should be a requirement in order to build an Installer. Or if by chance it is just a bug.

but here is the code where the problem occurs

`
if rc != 200:
            print "INFO: couldn't get tags."
            exit(1)
`

this just causes the builder to freeze if it cannot get the data it needs

and here is the code modified to bypass this and complete the build process

`
if rc != 200:
            print "INFO: couldn't get tags."
            #exit(1)
            return
`

it is a very simple solution and again I am not sure if this an actual bug or by design

**Comment by blackwind** [comment] 2016-08-27 06:40
It's by design. We don't want releases going out without a changelog, so we don't want to provide a means for skipping over building one. Fixing it in the manner you suggest would be even worse, as the log will just happily scroll by, leaving the user completely oblivious to what just happened.

The good news is:

* You only have to provide a username and a token.
* The token doesn't need to have any permissions assigned to it.
* You don't even need to build an installer to run from source.

**Closed by blackwind** 2016-08-27 06:40 UTC
Labels: bug, invalid

**Comment by kdschlosser** [comment] 2016-08-27 06:45
then some kind of notification as to why the build failed instead of just the "INFO: couldn't get tags" would be most helpful to inform the person that is compiling it of what the actual error is which would be that it couldn't get the needed information from a github account that is required to be set up. and if such a requirement is in place then why even start the build process at all if it hasn't been provided??

**Comment by blackwind** [comment] 2016-08-27 06:48
That's a fair criticism. I'll commit a more helpful error message.

**Comment by blackwind** [comment] 2016-08-27 08:46
Done in 126cf45.

**Comment by topic2k** [comment] 2016-08-27 13:03
Maybe instead of binding the changelog generation to the installer build task, we can bind it to the release to github task? That way one can generate an installer for testing but not release it without changelog.

**Comment by kdschlosser** [comment] 2016-08-27 16:08
Thanks boss. Took me a while to figure out why it was kicking out.

**Comment by blackwind** [comment] 2016-08-28 00:41
> Maybe instead of binding the changelog generation to the installer build task, we can bind it to the release to github task? That way one can generate an installer for testing but not release it without changelog.

Bit of a dirty solution there, as it requires a rebuild after you've already tested your original. What if you made a small change and forgot? What if you updated a package? What if [any number of other things]?

I think ca3a268 is the best possible compromise, so we'll go with that.

**Comment by kdschlosser** [comment] 2016-08-28 03:51
something to give a message about having to put in the github credentials as a popup if you are using the gui and none are entered and have it kick you back to the gui to enter the information would be great and if not using the gui just print a message and halt the build
