### ISSUE TITLE
Eventghost displays everything in "Slovak" language despite my system's default language being English

### ISSUE THREAD

**Issue by focus16gfx** [EventGhost/EventGhost#322] opened 2018-10-18 20:59 UTC
Just installed Eventghost and I have this problem. I have tried uninstalling and re-installing multiple times but the problem persists.    

I've assumed that the language is Slovak because that's what Google Translate said.

**Comment by focus16gfx** [comment] 2018-10-19 04:59
Thanks for responding.

Trying to open Options shows me various errors on the left side(Logger(?)). (Multiple Red Texts with Cross Sign(X)).

I'm sorry, I do not know how to find logs with the app being forced to display in Slovak so I'll post the screenshot.
https://i.imgur.com/qo43buY.png

**Comment by kdschlosser** [comment] 2018-10-19 07:01
you have something wrong in your locale settings for windows.
close EventGhost if you have it open.
follow these direction step by step. do not skip any,. 

windows is kind of set up goofy as far as the locale and language bits go.

start -- > control panel --> region and language
at the top of the dialog you will see 

    Format:

with a dropdown list under it. be sure this is set to your language and location.. if applicable. as an example. English has many locations.

next tab is Location. set this to your current location.

next tab. Keyboards and Language. 
be sure you have the proper keyboard layout selected. also make sure that you have the primary one (if there are multiple listed) moved to the top of the list. make sure you have the default language set properly.

This is where it gets all kinds of strange.
Because you can actually type in one language while reading in another and have all of the text and digit formatting for a completely different region of the world. and then st a completely different language for non unicode applications (legacy applications). I do not know what in the hell someone was thinking when they designed this whole disaster.

Next tab. Administrative. you want the Change System Locale button. select the proper country.

There is a pretty good chance that EG has saved the language data to your config file. I am going to walk you through how to manually adjust it.

open Windows Explorer (File Explorer). in the address bar at the top type in

    %appdata%\EventGhost

and press the enter key. this is going to bring you to the EventGhost application settings folder.
In that folder you will see a file called

   config.py

you want to edit that file. You will need  a text editor that is a wee bit better then notepad for this task. I would recommend you download notepad++ DO NOT USE WORDPAD or any other "word processor" for that matter.

you will see a line in that file that begins with 

    language = 

I am going to assume since you are typing in English you can read it as well LOL

make sure this line reads.

    language = 'en_EN'

do not forget the single quotes around the en_EN
save the file and then start up EG. and see how it goes.

Let me know how you make out.

Tip of the day: You can paste screen shots right into the comment box on github

**Comment by kdschlosser** [comment] 2018-10-19 07:13
@topik2k

Hey bud.. remember like 2 years ago.. when I had made a PR for setting the locale properly. The PR has sat for a bit and when you went over it and asked me about it. I said it was to fix a problem.. an for the life of me I could not remember what the problem was. nor could be produce any kind of an issue... 

Here it is.. I think we are detecting some odd setting in windows and not the actual language that is being displayed on the screen. I did this all once before and I know i fixed this issue. But since the PR was canceled and the branch deleted I cannot remember what in the world i did to fix the problem. I know it took me a bit of time to make it all work properly. It was quite aggravating if i remember correctly. I fixed it once.. I am going to pass the buck onto you to fix this issue this time. LOL. I know the changes were made in the eg.Utils file. 

This is the reason why.. 

https://docs.microsoft.com/en-us/windows/desktop/api/winnls/nf-winnls-getsystemdefaultlocalename

read the top. using wx to get the language gets the defauly "System" language. not the default "User" Language. The problem stems from say using a Russian copy of Windows the system default is going to be Russian. But you have all of the locale settings set to English. I am starting to remember the problem. I do not know if this issue is because of this or not. it could simply be a setting that is messed up. 

But there is a problem with the locale settings in EG. I am 100% sure of it.

**Comment by kdschlosser** [comment] 2018-10-19 08:08
ok so here is the fix. I was bored.

    def GetClosestLanguage():
        """
        Returns the language file closest to system locale.
        """
        import ctypes
        from ctypes.wintypes import BOOL, DWORD, ULONG, WCHAR
    
        MUI_LANGUAGE_NAME = 0x00000008
        NULL = None
    
        kernel32 = ctypes.windll.Kernel32
    
        GetUserPreferredUILanguages = kernel32.GetUserPreferredUILanguages
        GetUserPreferredUILanguages.restype = BOOL
    
        langDir = join(dirname(abspath(sys.executable)), "languages")
        if not exists(langDir):
            return 'en_EN'
    
        def check_lang():
            if exists(join(langDir, lang + ".py")):
                return lang
            else:
                for f in [f for f in os.listdir(langDir) if f.endswith(".py")]:
                    if f.startswith(lang[0:3]):
                        return f[0:5]
            return 'en_EN'
    
        dwFlags = DWORD(MUI_LANGUAGE_NAME)
        pulNumLanguages = ULONG(0)
        pwszLanguagesBuffer = NULL
        pcchLanguagesBuffer = ULONG(0)
    
        res = GetUserPreferredUILanguages(
            dwFlags,
            ctypes.byref(pulNumLanguages),
            pwszLanguagesBuffer,
            ctypes.byref(pcchLanguagesBuffer)
        )
    
        if res:
            pwszLanguagesBuffer = ((WCHAR * pcchLanguagesBuffer.value) * pulNumLanguages.value)()
            pcchLanguagesBuffer = ULONG(pcchLanguagesBuffer.value)
            pulNumLanguages = ULONG(pulNumLanguages.value)
    
            res = GetUserPreferredUILanguages(
                dwFlags,
                ctypes.byref(pulNumLanguages),
                ctypes.byref(pwszLanguagesBuffer),
                ctypes.byref(pcchLanguagesBuffer)
            )
            if res:
                lang = pwszLanguagesBuffer[0][:pcchLanguagesBuffer.value]
            else:
                lang = 'en_EN'
        else:
            lang = 'en_EN'
    
        return check_lang()


:-D

**Comment by focus16gfx** [comment] 2018-10-19 16:31
@kdschlosser    
Thank you so much. Your detailed instructions seemed to have solved my problem. Now the application reads in English.       
In the "config.py" file, I've noticed that there isn't a language line. So, I've added the  " language = 'en_EN' " after the version line.  It fixed the language isse.
Thanks again.

**Comment by kdschlosser** [comment] 2018-10-19 17:03
no worries m8, this is why we are here. But you also sparked something I had forgotten a long while ago that I believe we may need to put into EG. so we actually helped each other out,

**Comment by topic2k** [comment] 2018-10-20 12:48
@focus16gfx  can you please do me a favour and run [this script](https://gist.github.com/topic2k/52924491efa9aa4ef72b3d6b11b79415/archive/86ffe3af6f887d0cf18cd97f1ee5c791282f6642.zip)? Open a commandline, cd to the EG installation directory, type `py27 check_language.py` and paste the output here. I'm curious and trying to better understand what's going on.

@kdschlosser i think you mean #130. That code is a bit shorter and seems to give correct results.

**Comment by kdschlosser** [comment] 2018-10-20 14:06
I restored that branch. i forgot that locale has a cross reference from windows LANGID's to string language. that is the reason why i did the code above. because that is the only way to use the windows API to get the string language id. Windows does not have a LANGID to string function. and the GetUserDefault returns the LANGID. but you are correct the other version is much better.

I knew there was a problem with the language thing when i made that PR. and I now remember what the problem is. and it does need to get fixed. 

If you want i will create a new PR for it.

**Comment by topic2k** [comment] 2018-11-25 11:49
should be fixed in #325

**Closed by topic2k** 2018-11-25 11:49 UTC
