### ISSUE TITLE
Access denied on updating plugins via import of egplugin file

### ISSUE THREAD

**Issue by ThomasBott** [EventGhost/EventGhost#232] opened 2017-05-21 22:01 UTC
I'm getting an access denied error when I try to update one of my plugins that's already installed by using an egplugin file.

23:56:36   Traceback (most recent call last) (0.5.0-rc2):
23:56:36     File "wx\_core.pyc", line 16766, in <lambda>
23:56:36     File "C:\Program Files (x86)\EventGhost\eg\Utils.py", line 441, in LogItWithReturnWrapper
23:56:36       result = func(*args, **kwargs)
23:56:36     File "C:\Program Files (x86)\EventGhost\eg\Classes\PluginInstall.py", line 169, in Import
23:56:36       shutil.rmtree(info.path, False)
23:56:36     File "shutil.pyc", line 247, in rmtree
23:56:36     File "shutil.pyc", line 252, in rmtree
23:56:36     File "shutil.pyc", line 250, in rmtree
23:56:36   WindowsError: [Error 5] Zugriff verweigert: u'C:\\ProgramData\\EventGhost\\plugins\\AudioEndpoint\\AudioEndpointControl\\EndpointvolumeAPI.py'

Maybe it's because I import a library along with the plugin, didn't check that in detail.

Import works then I remove the plugin folder before importing.

EG 0.5 RC 2

**Comment by kdschlosser** [comment] 2017-05-21 22:03
this might be because you are using windows 10 and have the plugin installed into the core plugins directory. and when you go to install via the egplugin file it installs the new/updated version into the user plugins directory. and then will try to delete the old directory that is in the core plugins directory and windows will not allow an application to modify the program files directory

**Comment by ThomasBott** [comment] 2017-05-21 22:07
Nope, just double checked it, there is none in ProgramFiles, only one in ProgramData...
And it works when I delete that one manually

**Comment by kdschlosser** [comment] 2017-05-22 03:03
hmmm.... if the PR for all of  the work I have done to the plugin install had been merged we could have had a more detailed error message
but i am really leaning twords a permissions thing. as an example if you have installed a plugin whether manually or by using the eg plugin file as an administrator. but are then trying to update the plugin as a normal user you could get an error upon removing the plugin. this wuld be due to permissions. 

Are you running windows 10? 
Do you think that possibly the above scenario could have taken place?

maybe what we need to do is to set EG to suggest a restart as admin if running on Windows 10. if this issue is windows 10 specific. I have installed and upgraded a whole lot of plugins on Windows 7 and have only had an error come up one time and it was because of something I had done. But with Windows 10 it has changed how a whole lot of things work. almost so to the point of having to notify users that plugins that are not apart of the core will not be loaded if they are located in the core plugins directory. and inform them they will have to move them to the user plugins folder. you would need to check folder permissions.

After you remove the folder manually and then start eg and install the plugin all goes well i am assuming?
Have you tried  to update the plugin again to see if the error comes back?
Are you running EG as Administrator when you do this?

**Comment by ThomasBott** [comment] 2017-05-22 09:52
I do use Windows 10.
I was able to remove the plugin folder with my normal user rights manually (UAC is active), I don't think it's a problem with folder permission, but I'll check that

Yes, when the plugin doesn't exist all goes well.
As detailed in the other issue, the import doesn't work if running EG as admin...

I'll try to do some more tests this evening with other plugins.

**Comment by ThomasBott** [comment] 2017-05-22 19:07
Hmm, can't reproduce it anymore... It's strange because I tried it multiple times yesterday...

**Closed** 2017-05-22 19:09 UTC

**Comment by kdschlosser** [comment] 2017-05-22 23:44
No reason to close it. the issue is not solved. Something must have caused it you just haven't found the exact process yet.

well i guess if you do find what caused it then you can reopen it
