### ISSUE TITLE
Copy & Paste from the forum

### ISSUE THREAD

**Issue by Diz-57** [EventGhost/EventGhost#233] opened 2017-06-01 14:58 UTC
when copy & pasting from the eventghost forum if you use that little 'select all' button at the top it always puts an extra indent in from the left edge.   but if you drag the mouse over the text yourself to copy it then the left edge is where it is supposed to be.

**Comment by kdschlosser** [comment] 2017-06-02 12:32
I am running tests on this to see what the cause is. But at first glance it seems as tho the copied data isn't event making it into EG to be evaluated before it can be pasted. Which I find very odd and could be a bug in wx. I am still working on this.

**Comment by Diz-57** [comment] 2017-06-02 13:11
ok... sounds more complicated than it first appeared then! lol

**Comment by per1234** [comment] 2017-06-02 22:24
Is this problem specific to the EventGhost application? I remember encountering it but I thought it happened no matter where you pasted the copied code, even if that was just a regular text editor so I thought the problem originated with the forum software.

Now I can't reproduce because when I click the "SELECT ALL" button on any code box on the forum it just jumps me to the top of the page and doesn't select anything. That happens in Firefox and Chrome browsers.

**Comment by Diz-57** [comment] 2017-06-03 02:29
yes you are right it is not specific to eventghost.  i realised what the problem was when i pasted into notepad instead of eventghost.  i first reported it at the forum actually but was told to post an issue here so he wouldnt forget to fix it!  lol

i am using firefox and i do not get the behaviour you report by the way.  for me with firefox the copy is done but with the unwanted extra indents.

**Comment by kdschlosser** [comment] 2017-06-03 16:36
it is most likely with the forum software no doubt. and since the forum is the main line of support for EG unless someone know phpbb up close and personal to assist in fixing the issue it might be easier to make accommodations in EG for it instead, now I know it wouldn't be the correct way to go about fixing the issue but it would make the paste work. actually per you would probably do very well at php being as tho it looks almost identical to CPP and I know you are a very busy and this is not a pressing issue but I could set up a moc up server and we could tinker with it to see if we could get it repaired the proper way if you are willing to lend a hand. this is not something that would be top priority as it has been broken for a long time and there is a way around it at the moment.

**Comment by kdschlosser** [comment] 2017-06-03 17:23
well good new is i i have the fix. tho it will have to wait until this evening before i run it and see if all is good. 
and it will be fixed at the forum level and not in eg

**Comment by Diz-57** [comment] 2017-06-03 18:23
Great news!

**Comment by kdschlosser** [comment] 2017-06-03 18:26
this issue is keyed to specific browsers and versions. and it has to deal with how the information is selected technically speaking the "bug" is not in the forum software or in EG. it is actually in the browser it's self. but there is a means to check for this issue and work around it at the forum level when the data is being selected. tonight I will put this into place to see if it solves the issue.

**Comment by kdschlosser** [comment] 2017-06-04 06:28
This should now be fixed. here is a link to the forum with a test, be sure to follow the instructions.

http://www.eventghost.net/forum/viewtopic.php?f=12&t=9699&p=46353#p46353

**Comment by Diz-57** [comment] 2017-06-04 12:48
confirmed working here on firefox esr 52.1.2 (32-bit)

**Comment by kdschlosser** [comment] 2017-06-04 18:07
fixed!

**Closed by kdschlosser** 2017-06-04 18:07 UTC
Labels: bug, internal
