### ISSUE TITLE
MainMessageReceiver problem with ChangeClipboardChain

### ISSUE THREAD

**Issue by saue0** [EventGhost/EventGhost#226] opened 2017-05-02 16:53 UTC
The ChangeClipboardChain do not seem to be call.
  The workaround was Removing it from Stop into Finish.

Can someone verifie this.

Thanks

**Comment by kdschlosser** [comment] 2017-05-04 05:53
I have no idea what you are having an issue with.

I need errors, a better description of the problem. screen shots. I need something other then a very vague description to be able to help ya out. My best guess is that you removed it from MainMessageReceiver.py but you do not explain what the problem was

**Comment by saue0** [comment] 2017-05-05 10:46
The problem is that evenghost do not unregister it self from the clipboard chain , it's like if the stop procedure do not get call. By moving the  ChangeClipboardChain in the finish procedure, eventghost get unregisted. This poblem cause other program that capture the clipboard change (ex Ditto) to stop receiving notification after eventghost is stopped, The chain is break.

**Comment by kdschlosser** [comment] 2017-05-06 06:56
give a way to replicate this problem using a common program like notepad or wordpad

**Comment by kdschlosser** [comment] 2017-05-06 15:27
I downloaded that clipboard program Ditto that you mentioned.. I copied some text and it appeared in Ditto. then i started EG and copied some text and it appeared in Ditto. then i closed EG and copied some text and it appeared in Ditto. So i am not sure exactly what the problem is.. I am thinking that is what you meant. but everything seems to work just fine.

**Comment by kdschlosser** [comment] 2017-05-06 15:28
it could have something to do with you OS??... what version of windows are you running? I tested this on a Windows 7 computer. It could be a Windows 10 thing if that is what you are running.

**Comment by saue0** [comment] 2017-05-06 15:58
I'm using windows 10, I will retry monday with the latest version of EG. 
How can I add log info in the stop procedure ? 
"print" do not work because EG is stopping.  need to log in a file.

**Comment by kdschlosser** [comment] 2017-05-06 18:10
it is being logged there is a decorator @eg.LogIt before the action that gets called is there is a clipboard chain change. 

so what is supposed to happen is when EG gets closed the Stop() method gets called and the ChangeClipboardChange command gets called to Change the chain. and when that happens windows is supposed to send out a notification to all windows that are set to receive these notification and the callback is OnChangeClipboardChain. which should be logged in the debugging log. which can be turned on if you start EG from a commandline with the -debug switch and the file is located in %appdata%\EventGhost as Log.txt

 trigger a windows event

**Comment by saue0** [comment] 2017-05-06 19:01
Thanks will try and get back soon.

**Comment by kdschlosser** [comment] 2017-05-08 14:04
any new information on this?

**Comment by saue0** [comment] 2017-05-08 17:11
The only explication I have is that the stop vs finish is not call in the same thread

13:05:57: 1 MainThread: MainMessageReceiver --> Stop
13:05:57: 1 MainThread: Handle --> 4593682:1706540
13:05:57: 0 MainMessageReceiver: MainMessageReceiver --> Finish
13:05:57: 0 MainMessageReceiver: Handle --> 4593682:1706540


    @eg.LogItWithReturn
    def Finish(self):
        eg.PrintDebugNotice('MainMessageReceiver --> Finish')
        eg.PrintDebugNotice('Handle --> ' + str(self.hwnd) + ':' + str(self.hwndNextViewer))
        #ChangeClipboardChain(self.hwnd, self.hwndNextViewer)
        eg.MessageReceiver.Finish(self)

    @eg.LogItWithReturn
    def Stop(self):
        eg.PrintDebugNotice('MainMessageReceiver --> Stop')
        eg.PrintDebugNotice('Handle --> ' + str(self.hwnd) + ':' + str(self.hwndNextViewer))
        ChangeClipboardChain(self.hwnd, self.hwndNextViewer)
        eg.MessageReceiver.Stop(self)


Time is up for testing, will try more tomorrow

**Comment by kdschlosser** [comment] 2017-05-08 19:02
I need to see the whole log. not just a couple of line from it. I need to know how other parts of EG are shutting down as well.

you can attach the log file. 

also I am not sure where this chunk of code comes from but is defiantly not in the MainMessageReceiver.py

    @eg.LogItWithReturn
    def Finish(self):
        eg.PrintDebugNotice('MainMessageReceiver --> Finish')
        eg.PrintDebugNotice('Handle --> ' + str(self.hwnd) + ':' + str(self.hwndNextViewer))
        #ChangeClipboardChain(self.hwnd, self.hwndNextViewer)
        eg.MessageReceiver.Finish(self)

**Comment by saue0** [comment] 2017-05-08 19:25
This is the part I added for debugging help.
I included the log and the modified MainMessageReceiver.py

[MainMessageReceiver.py](https://github.com/EventGhost/EventGhost/files/984589/MainMessageReceiver.py.txt)
[Log.txt](https://github.com/EventGhost/EventGhost/files/984617/Log.txt)

**Comment by kdschlosser** [comment] 2017-05-08 19:33
but yes they are supposed to be called from different threads, But Finish when it gets called for the MainMessage Receiver all it does is Destroy the window that receives the notifications

that would not be where the chain issues comes from.


so this is how this whole thing works....

you have a grandparent class of eg.ThreadWorker, a parent of eg.MessageReceiver and the child is MainMessageReceiver. so there are 3 different places to cover to get the whole Stop() procedure


Stop() gets called and when it does it is done so by the main thread
This sends a notification to windows that the chain is going to be changed.

    ChangeClipboardChain(self.hwnd, self.hwndNextViewer)

This calls the parent class to start the Stop procedures for the MainMessageReceiver

    eg.MessageReceiver.Stop(self)

This is the remainder of the Stop()

    self.messageProcs.clear()
    eg.ThreadWorker.Stop(self, 5.0)
    if not UnregisterClass(cast(self.classAtom, LPCTSTR), GetModuleHandle(None)):
        raise WinError()

and now you can see where the grandparent Stop() gets called

    eg.ThreadWorker.Stop(self, 5.0)

and here is Stop() from the grandparent
    def StopCall():
        self.__alive = False

    self.Call(StopCall)
    if timeout > 0.0:
        self.__thread.join(timeout)
        return self.__thread.isAlive()

Now what takes place here is the 

    self.Call(StopCall)

puts the function StopCall into the queue to be run by the MainMessageReceiver thread. which gets run. and that in turn sets the self.__alive to false so the loop can be closed as indicated in the method __MainLoop

    CoInitializeEx(None, COINIT_APARTMENTTHREADED)
    self.__PumpWaitingMessages()
    try:
        while self.__alive:
            self.__DoOneEvent()
    finally:
        self.Finish()
        CoUninitialize()

that is when self.Finish() gets called inside of the MainMessageReceiver thread.

and that is when the window gets descroyed as shown in the Finish() method of the parent

    if not DestroyWindow(self.hwnd):
        raise WinError()
    self.hwnd = None

Now.. what i suspect is going on is because windows has been notified to change the clipboard chain. Now this is what I am thinking. some dingdong who coded some other bit of software put a whole heap ton of code into their callback of the clipboard chain changing. because windows will not move on to notify the next program until it has been released from the current one. and if someones program is taking forever to do this then EG would have already closed before windows managed to get a notification to it.. So directly this is not the fault of EG but the fault of some other piece of software you are running. 

Now can EG be made to deal with the issues that some other piece of software is causing.. Yes sir it can be.. but the question is should it be?? my personal opinion is No. The reason for this is because the person that coded the other software needs to fix their code. so with some effort you should be able to locate which piece of software it is  and then go talk to them about cleaning up the code in their change clipboard chain callback so it doesn't cause the windows notification system to come to a screeching halt

Now you can also fix this problem by starting EG before you start that other piece of software. this will remedy the problem as well.












 is what is supposed to set the chain properly. Now... that being said.. it doesn't sit there and wait. this is a windows notification and windows is supposed to respond back so if your windows is not responding back in a timly manner.. EG si going to close before it receives notification from windows to repair the clipboard chain.


so the notification

**Comment by saue0** [comment] 2017-05-08 19:55
The other software is A delphi program that i wrote myself.
If the ChangeClipboardChain is in the Stop, I do not get the "OnChangeClipboardChain" message,
BUT if i put it in the Finish. I get notified.

I will do more testing with Delphi and thread, to see if the ChangeClipboardChain must be call in the same thread of the SetClipboardViewer.

I will also do some test with Ditto. instead of my Delph program.

Will get back soon..

Thanks for all this help.

**Comment by kdschlosser** [comment] 2017-05-08 20:05
No do not bother...

this comment made me go looking

    if the ChangeClipboardChain is in the Stop, I do not get the "OnChangeClipboardChain" message,
    BUT if i put it in the Finish. I get notified.

since the advent of windows 10. it has become a real stickler for the same thread that registered for the notifications be the same one that also closes the notifications. and the really pain part about it is you get no errors just some really odd behavior sometimes.

By your simple action of moving the ChangeClipboardChain from the stop to the finish moved the unregistering from the Main thread to the MainMessageReceiver thread.

My question is. does this solve the problem?

**Comment by saue0** [comment] 2017-05-08 20:25
Yes...lol...

**Comment by kdschlosser** [comment] 2017-05-08 21:50
I am going to fix the problem. But I am going to make sure your name gets attached to it. You are the one that discovered it and provided the fix.. I am going to change the fix a little bit. but you will be able to see the code. I will post a link here so you can download a installer for EG with the fix included. this will have all updates until now included in the build. Give me a few to get all this together

**Comment by kdschlosser** [comment] 2017-05-08 22:11
ok here is the new setup. so give it a go. I also added a threading lock this way the actual window that receives the notification about the clipboard change doesn't get closed until the change notification comes in. then at that time the lock is released and the notification window can get closed

here is the link. give this a go and let me know if it works. if it does i will submit a Pull Request anf make sure you get the credit for it.

https://ci.appveyor.com/api/buildjobs/lm1c8lc9isppj052/artifacts/_build%2Foutput%2FEventGhost_WIP-2017.05.08-22.06.38_Setup.exe

**Comment by kdschlosser** [comment] 2017-05-09 02:12
ok scratch the last build. i have to let it do it's think i have to remove the locks

**Comment by kdschlosser** [comment] 2017-05-09 06:47
https://ci.appveyor.com/api/buildjobs/3xmioug9xfccnysl/artifacts/_build%2Foutput%2FEventGhost_WIP-2017.05.09-06.17.27_Setup.exe

here is a build that doesn't error. give it a shot and see if it works for you

**Comment by saue0** [comment] 2017-05-09 12:30
It work. Thanks
For my onw knowledge  2 questions:
1- Why not use the Finish fuction for the cleenup ?
2- what does self.Func() do ?

**Comment by kdschlosser** [comment] 2017-05-09 15:17
self.Func is a way to get any function and it's arguments to be run in that thread. similar to the way wxCallback works to get things to run in the MainThread except this  will wait until your function actually runs. before returning the reason why i didn't move it to Finish because that would change the order in which things get done. and I wanted to keep it the same.

**Comment by saue0** [comment] 2017-05-09 16:42
Thanks.

**Closed** 2017-06-12 19:03 UTC
Labels: bug
